# suppress inspection "UnusedProperty" for whole file
Plain\ text = text/plain
ActionScript = text/actionscript
Assembler(x86) = text/asm
Assembler(6502) = text/asm6502
BBCode = text/bbcode
C = text/c
Clojure = text/clojure
C++ = text/cpp
C# = text/cs
CSS = text/css
CSV = text/csv
D = text/d
Dockerfile = text/dockerfile
Dart = text/dart
Delphi/Pascal = text/delphi
DTD = text/dtd
Fortran = text/fortran
Go = text/golang
Groovy = text/groovy
Handlebars = text/handlebars
Hosts = text/hosts
.htaccess = text/htaccess
HTML = text/html
INI = text/ini
Java = text/java
JavaScript = text/javascript
JSON = text/json
JSON(comments) = text/jshintrc
JSP = text/jsp
Kotlin = text/kotlin
LaTeX = text/latex
Less = text/less
Lisp = text/lisp
Lua = text/lua
Makefile = text/makefile
Markdown = text/markdown
MXML = text/mxml
NSIS = text/nsis
Perl = text/perl
PHP = text/php
PowerShell = text/powershell
Proto = text/proto
Properties = text/properties
Python = text/python
Ruby = text/ruby
Rust = text/rust
SAS = text/sas
Scala = text/scala
SQL = text/sql
Tcl = text/tcl
TypeScript = text/typescript
Unix\ Shell = text/unix
Visual\ Basic = text/vb
VHDL = text/vhdl
Batch = text/bat
XML = text/xml
YAML = text/yaml